# Generated by Django 4.2.7 on 2024-06-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.DateField()),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nome', models.CharField(max_length=155)),
                ('sobrenome', models.CharField(max_length=100)),
                ('rnm', models.CharField(max_length=16)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=64)),
            ],
        ),
    ]
